### ISSUE TITLE
Seems to be infinite loop in getting list of staked blocks

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#112]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/95aa8a54-40d1-488a-9d72-6ca9f762421c)

Limit it to last 20 blocks

**Comment by imylomylo** [comment]
console shows 1000+ blocks in history continuing to be loaded.

**Comment by iamahmedshahh** [comment]
Fixed missing .env variable `VITE_APP_BLOCKS=20`
