### ISSUE TITLE
invert button does not work

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#20]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/21fe6474-fac4-4b31-bbb3-8f3bf2add647)

![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/2ccb93cd-20a8-43d7-9091-b4db3f81ba6e)

**Comment by iamahmedshahh** [comment]
Pull Request #26
