### ISSUE TITLE
dashboard swap history overlay not working

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#21]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/7ce7d803-628a-4c00-91f7-c955e5bf2529)

![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/13171a6b-6c44-4740-a5f4-66dac4a142aa)

show / hide functionality

**Comment by iamahmedshahh** [comment]
https://github.com/iamahmedshahh/mm2v3/commit/1b5f8cbd4e9a8cfcc11b7ab1309223749d174230
