### ISSUE TITLE
dashboard wallets actions not same as old version with same config

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#22]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/295067a9-44ac-4b12-b25a-fd20694f18e3)

![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/2fe4a1b8-f667-4ab4-bee9-29c8f45eaa52)

maybe an env var is not being passed in or read or code is missing

**Comment by iamahmedshahh** [comment]
Same setting as the single order

`export default {
  components: { QrcodeVue },
  props: [ 'wallets' ],
  data: function() {
    return {
      mePrivate: process.env.VITE_VUE_APP_MEPRIVATE,
      mePublic: process.env.VITE_VUE_APP_MEPUBLIC,
      absoluteOverlay: false,
      depositOverlay: false,
      depositOverlaySize: 400,
      depositTicker: "",
      depositAddress: "",
      hideZero: false,
      hideZeroDisable: true,
      customerrors: [],
    };`
    
    You are passing the variables here. There is a div v-if condition being used. Like the following:
    
    `div v-if="mePrivate == 'true' && mePublic == 'false'">
              <v-chip class="ma-2" color="success" @click="deposit(row.ticker, row.address)">
                <v-icon left>mdi-server-plus</v-icon>Deposit
              </v-chip>
              <v-chip class="ma-2" color="red" dark @click="showWithdrawOverlay(row.ticker)">
                <v-icon left>mdi-server-plus</v-icon>Withdraw
              </v-chip>
</div>
<div v-else>
              <v-chip class="ma-2" color="success" @click="deposit(row.ticker, row.address)">
                <v-icon left>mdi-server-plus</v-icon>Donate
              </v-chip>
</div>`

Now this is the .env settings:

VITE_VUE_APP_MMBOTURL=http://localhost:5173/
VITE_VUE_APP_MEPRIVATE=http://localhost:5173/
VITE_VUE_APP_MEPUBLIC=http://localhost:5173/
VITE_VUE_APP_MENAME=http://localhost:5173/
VITE_VUE_APP_WEBHOST=http://localhost:5173/
VITE_VUE_APP_MMBOTHOST=http://localhost:5173/
VITE_VUE_APP_MMBOTPORT=16077

**Comment by imylomylo** [comment]
check env.sample for guidance on what MEPRIVATE & MEPUBLIC should be set to. https://github.com/KomoDeFi/komodefi-app/blob/develop/env.sample

**Comment by iamahmedshahh** [comment]
```
mePrivate: process.env.ME_PRIVATE,
mePublic: process.env.ME_PUBLIC,
```

my .env

```
VITE_VUE_APP_MMBOTURL=http://localhost:5173/
ME_PRIVATE=true
ME_PUBLIC=false
VITE_VUE_APP_MENAME=http://localhost:5173/
VITE_VUE_APP_WEBHOST=http://localhost:5173/
VITE_VUE_APP_MMBOTHOST=http://localhost:5173/
VITE_VUE_APP_MMBOTPORT=16077

```

**Comment by iamahmedshahh** [comment]
Fixed and added hover effects like the old version as well.
