### ISSUE TITLE
env var for private/public functionality not available for placing an order

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#23]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/3c031320-253c-4f98-837a-4ed15d61693c)

vs  

![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/5d2096e0-cc8c-4400-a85a-f6e67bc201f3)

**Comment by iamahmedshahh** [comment]
![Uploading Screenshot from 2023-05-31 02-44-30.png…]()

**Comment by iamahmedshahh** [comment]
Check

**Comment by imylomylo** [comment]
fixed. refer to #37 for keeping repo clean.
.env.sample would be useful for people to investigate what they need to set, that  are running on their local.
