### ISSUE TITLE
traderview automation overlay not working

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#24]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/6882f14f-c276-436b-9c0e-22df1698de83)

![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/3f061b4b-e6b9-412d-b7ed-2e2b8978f1e4)

overlay atm should always be on, so the settings for automation are not available.

**Comment by iamahmedshahh** [comment]
https://github.com/iamahmedshahh/mm2v3/commit/1b5f8cbd4e9a8cfcc11b7ab1309223749d174230
