### ISSUE TITLE
single order

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#28]
work on the single order dialog so an order is created

the order should also show up on the dashboard "Orders For This Node" widget

**Comment by iamahmedshahh** [comment]
![Screenshot from 2023-05-31 02-44-30](https://github.com/iamahmedshahh/mm2v3/assets/82913912/16a7fbde-3c8f-49ca-a111-2acc16ed3628)

**Comment by imylomylo** [comment]
maybe related to the correct behaviour of true/false on MEPRIVATE MEPUBLIC settings related to https://github.com/iamahmedshahh/mm2v3/issues/22#issuecomment-1573986643

when public is true, order dialog should not show.

**Comment by iamahmedshahh** [comment]
#32 Last commit to the Junefixes

**Comment by imylomylo** [comment]
seems to honour the env passed in from docker. good stuff.
there is a .env file that is being committed to repo that will need to be put into the .gitignore file, because it stuffs up deployments for the unsuspecting deployer.
