### ISSUE TITLE
padding for heading automated mm

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#30]
traderview
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/ad416ed8-3973-4b8e-82ad-34b8e5f58af9)

**Comment by iamahmedshahh** [comment]
check

**Comment by imylomylo** [comment]
looks the same - don't have a commit reference
if the commit message has something like `#30 padding fixed` it would link automatically here, so the commit can be cross referenced, then the deployed code can be checked against the commit.
currently it's looking for something that is not familiar - and takes too long.

**Comment by iamahmedshahh** [comment]
https://github.com/iamahmedshahh/mm2v3/commit/38154b2ce8d74a12d2ea94855e70d46064013b24
