### ISSUE TITLE
hardcoded go to market link

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#33]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/795a43d8-865d-4ee4-a3fe-5789f21fb0c5)

**Comment by imylomylo** [comment]
after removing the hardcoded RICK/MORTY, i tested it and the passed in tickers update the GUI for the user to show they are selecting whatever markets they care to view - e.g. in my case BTC/DOGE

the comment in the console respects this selection in the `gotoMarketetView()` @click event, but it throws an error - and somehow ends up in RICK/MORTY

![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/19f533bf-d2e0-4d5f-8ea5-f2826d316f25)

**Comment by iamahmedshahh** [comment]
Because I added the static Rick and Morty somewhere in the code thinking hardcoded is for testing purposes I will take a look
