### ISSUE TITLE
mouseover on orders for this node widget missing cursor change

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#36]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/456123f6-4ba5-4433-aa47-a4a573c9bb7a)

**Comment by iamahmedshahh** [comment]
Fixed with Point cursor kindly check the [Commit](https://github.com/iamahmedshahh/mm2v3/commit/65d64868661a7317e012ac9b424d2f7318782ff3)
