### ISSUE TITLE
add .env to .gitignore so it does not pollute the docker-compose deployments

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#37]
comment closing issue #28 mentions this

**Comment by iamahmedshahh** [comment]
Removed from repo and added in [gitignore](https://github.com/iamahmedshahh/mm2v3/commit/c6c4cb4cb11d2ae2836feebed06de4903e3fd842)

**Comment by iamahmedshahh** [comment]
Apparently the removal of .env does cause effects on the project I think the project is using the .env of the front end I think bad idea. Have a look at the app

**Comment by iamahmedshahh** [comment]
https://github.com/iamahmedshahh/mm2v3/commit/2d5bdd5c1488e70dd2eb0c27e36831d35288f07c
