### ISSUE TITLE
header active strategies too tight to the top border

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#6]

**Comment by iamahmedshahh** [comment]
check

**Comment by imylomylo** [comment]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/acf73c0f-4623-4aac-93aa-0fdaa46a4781)
same

**Comment by iamahmedshahh** [comment]
Check commit and front end https://github.com/iamahmedshahh/mm2v3/commit/75a7e817a827e9211b6612e43bedfd85aa8cedc9

**Comment by iamahmedshahh** [comment]
https://github.com/iamahmedshahh/mm2v3/commit/75a7e817a827e9211b6612e43bedfd85aa8cedc9
