### ISSUE TITLE
automated boolean/flag not honoured

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#61]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/cec5cf65-05cd-474d-ba6d-2c843c1d7de5)

whether automation is on or off does not seem to be read.  not sure if it is hard-coded to be 'no automation' in v2.
but there is no automation, so it should be 'no automation'

![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/9aebcfa6-a939-488a-b1b6-ae5df0731c0d)
v2 ^

**Comment by iamahmedshahh** [comment]
Changed to no automation, there is no functionality ATM to detect automation via overlay
