### ISSUE TITLE
wallets deposit/withdraw controls lost

### ISSUE THREAD

**Issue by imylomylo** [iamahmedshahh/mm2v3#99]
![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/955d61fd-a0bb-40f8-b913-6d5949790882)

but down the bottom they are in an aweful horizonal scroll

![image](https://github.com/iamahmedshahh/mm2v3/assets/19399102/4e1eb8ac-c4ea-44ae-90ea-2ad5fac1fc0b)

**Comment by iamahmedshahh** [comment]
Scrollable is better because if the width is max other components go out of scope.

**Comment by imylomylo** [comment]
Not to the user who doesn't scroll to the bottom then asks for support, wasting everyone's time including theirs for waiting or bailing on the app because of non smooth ux
